pipeline{
    agent any
    stages{
        stage("code"){
            steps{
                echo "HELLO CODE!"
            }
        }
        stage("Build"){
            steps{
                echo "HELLO BUILD!"
            }
        }
        stage("Deploy"){
            steps{
                echo "HELLO DEPLOY!"
            }
        }
    }
}